// Code generated by "stringer -type=SourceType"; DO NOT EDIT.

package component

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnsetSourceType-0]
	_ = x[JavaSourceType-1]
	_ = x[PythonSourceType-2]
}

const _SourceType_name = "UnsetSourceTypeJavaSourceTypePythonSourceType"

var _SourceType_index = [...]uint8{0, 15, 29, 45}

func (i SourceType) String() string {
	if i < 0 || i >= SourceType(len(_SourceType_index)-1) {
		return "SourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SourceType_name[_SourceType_index[i]:_SourceType_index[i+1]]
}
