// Code generated by "stringer -type=SourceType"; DO NOT EDIT.

package component

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnsetSourceType-0]
	_ = x[GemSourceType-1]
	_ = x[JavaSourceType-2]
	_ = x[NPMSourceType-3]
	_ = x[PythonSourceType-4]
	_ = x[SentinelEndSourceType-5]
}

const _SourceType_name = "UnsetSourceTypeGemSourceTypeJavaSourceTypeNPMSourceTypePythonSourceTypeSentinelEndSourceType"

var _SourceType_index = [...]uint8{0, 15, 28, 42, 55, 71, 92}

func (i SourceType) String() string {
	if i < 0 || i >= SourceType(len(_SourceType_index)-1) {
		return "SourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SourceType_name[_SourceType_index[i]:_SourceType_index[i+1]]
}
