# Originally copied from github.com/stackrox/stackrox, and regularly kept in-sync manually.

version: "2"
run:
  timeout: 16m
  go: "1.23"
  modules-download-mode: readonly
output:
  formats:
    text:
      path: stdout
    junit-xml:
      path: report.xml
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  default: none
  enable:
  - asciicheck
  - copyloopvar
  # - errcheck
  # - forbidigo
  - gocritic
  # - exptostd
  - gosec
  - govet
  - ineffassign
  # - modernize
  - nolintlint
  # - protogetter
  - revive # replaces golint
  - rowserrcheck
  - staticcheck
  # - wrapcheck
  # - nakedret TODO: add in follow-up
  - unconvert
  # - unparam TODO: add in follow-up
  settings:
    gosec:
      includes:
      - G601
    govet:
      disable:
      - shadow
      - fieldalignment
      enable-all: true
      settings:
        printf:
          funcs:
          - Print
          - Printf
          - Println
          - Debug
          - Debugf
          - Info
          - Infof
          - Warn
          - Warnf
          - Error
          - Errorf
    nolintlint:
      require-explanation: false
      require-specific: true
      allow-unused: false
    revive:
      rules:
      - name: package-comments
        disabled: true
      - name: error-strings
        disabled: true
      - name: unexported-return
        disabled: true
    staticcheck:
      checks:
      - all
      - -QF1001
      - -QF1002
      - -QF1003
      - -QF1008
      - -SA1019
      - -SA4001
      - -ST1000
      - -ST1001
      - -ST1003
      - -ST1005
  exclusions:
    generated: lax
    rules:
    - linters:
      - revive
      text: should have a package comment, unless it's in another file for this package
    - linters:
      - revive
      text: should not use dot imports
    - linters:
      - revive
      text: returns unexported type .* which can be annoying to use
    - linters:
      - revive
      text: error strings should not be capitalized or end with punctuation or a newline
    - linters:
      - revive
      text: should omit type int from declaration
    - linters:
      - revive
      text: don't use leading k in Go names
    - linters:
      - revive
      text: 'package-comments: should have a package comment'
    - linters:
      - gocritic
      path: _test\.go
    paths:
    - third_party$
    - builtin$
    - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
  - gofmt
  - goimports
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
