#!/bin/sh

set -e

if [ -d /usr/local/share/ca-certificates -a "$(find /usr/local/share/ca-certificates -name '*.crt' -maxdepth 1 | wc -l)" -gt 0 ]; then
  cp -L /usr/local/share/ca-certificates/* /etc/pki/ca-trust/source/anchors
  update-ca-trust
fi
