#!/bin/sh

set -e

if [ -d /usr/local/share/ca-certificates ] && [ "$(find /usr/local/share/ca-certificates -name '*.crt' -maxdepth 1 | wc -l)" -gt 0 ]; then
  # RHEL
  cp -L /usr/local/share/ca-certificates/* /etc/pki/ca-trust/source/anchors
  update-ca-trust
fi
