ARG BASE_IMAGE
ARG BASE_TAG

FROM BASE_IMAGE:BASE_TAG

RUN rm -rf "${NVD_DEFINITIONS_DIR}" && \
    rm -rf "${K8S_DEFINITIONS_DIR}" && \
    rm -rf "${REPO_TO_CPE_DIR}" && \
    rm -f genesis_manifests.json

ENV ROX_LITE_MODE="true"
