apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: fetch-scanner-data
  namespace: rh-acs-tenant
# TODO(ROX-22196): Make the task EC-compliant (e.g. move to a bundle)
spec:
  description: Downloads blobs from definitions.stackrox.io GCloud bucket to be included in Scanner container builds.
  params:
  - name: blobs-to-fetch
    description: |
      List of scanner-data file names to fetch to include in the container build.
      An empty list is allowed which results in no-op.
    type: array
  - name: target-dir
    description: Target directory relative to workspace where to save downloaded blobs.
    type: string
    default: "."
  - name: SOURCE_ARTIFACT
    description: The Trusted Artifact URI pointing to the artifact with
      the application source code. This should be the result of the git-clone task,
      results from other tasks might fail as dirty.
    type: string
  - name: ociStorage
    description: The OCI repository where the Trusted Artifacts are stored.
    type: string
  - name: ociArtifactExpiresAfter
    description: Expiration date for the trusted artifacts created in the
      OCI repository.
    type: string
  results:
  - name: SOURCE_ARTIFACT
    description: The Trusted Artifact URI pointing to the artifact with the application source code
      and additional smuggled activation key.
    type: string
  volumes:
  - name: workdir
    emptyDir: { }
  stepTemplate:
    volumeMounts:
    - mountPath: /var/workdir
      name: workdir
  steps:
  - name: use-trusted-artifact
    image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:62bb85585c0ebb8b333ef716b87b70838fb27723657c95ffb62d446b0d28ab68
    args:
    - use
    - $(params.SOURCE_ARTIFACT)=/var/workdir/source
  - name: fetch-scanner-data
    image: registry.access.redhat.com/ubi8/ubi-minimal:latest
    # The only functioning way to pass array parameter that I found is through args array.
    # Array params have weird limitations, see https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#substituting-array-parameters
    # Attempts to pass this in other places result in webhook errors and pipeline not starting.
    args: [ "$(params.blobs-to-fetch[*])" ]
    workingDir: /var/workdir/source
    script: |
      #!/usr/bin/env bash
      set -euo pipefail
      scripts/konflux/fetch-scanner-data.sh "$(params.target-dir)" "$@"
    # It should not take long to download blobs otherwise there's something odd going on.
    timeout: 10m
  - name: create-trusted-artifact
    image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:62bb85585c0ebb8b333ef716b87b70838fb27723657c95ffb62d446b0d28ab68
    args:
    - create
    - --store
    - $(params.ociStorage)
    - $(results.SOURCE_ARTIFACT.path)=/var/workdir/source
    env:
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.ociArtifactExpiresAfter)
