apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/scanner?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "500"
    # TODO(ROX-21073): re-enable for all PR branches
    pipelinesascode.tekton.dev/on-cel-expression: (event == "push" && target_branch == "master") || (event == "pull_request" && (source_branch.contains("konflux") || source_branch.contains("rhtap")))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: acs
    appstudio.openshift.io/component: scanner-db
    pipelines.appstudio.openshift.io/type: build
  name: scanner-db-build
  namespace: rh-acs-tenant

spec:

  params:
  - name: dockerfile
    value: image/db/rhel/konflux.Dockerfile
  - name: git-url
    value: '{{source_url}}'
  - name: image-expires-after
    value: '52w'
  - name: output-image-repo
    value: quay.io/rhacs-eng/scanner-db
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: rebuild
    value: 'true'
  # TODO(ROX-20234): Enable hermetic builds
  # - name: hermetic
  #   value: "true"
  # No language dependencies are required for scanner-db image.
  - name: prefetch-input
    value: ''
  - name: build-source-image
    value: 'true'
  - name: build-target-stage
    value: scanner-db
  - name: clone-depth
    value: '0'
  - name: clone-fetch-tags
    value: 'true'
  - name: blobs-to-fetch
    value: [ 'pg-definitions.sql.gz' ]

  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'

  taskRunSpecs:
  - pipelineTaskName: clamav-scan
    stepSpecs:
    # Provision more CPU to speed up ClamAV scan compared to the defaults.
    # https://github.com/redhat-appstudio/build-definitions/blob/main/task/clamav-scan/0.1/clamav-scan.yaml#L48
    - name: extract-and-scan-image
      computeResources:
        requests:
          cpu: 1

  pipelineRef:
    name: scanner-component-pipeline
