apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: scanner-component-pipeline

spec:

  finally:
  - name: show-sbom
    params:
    - name: IMAGE_URL
      value: $(tasks.build-image-manifest.results.IMAGE_URL)
    taskRef:
      params:
      - name: name
        value: show-sbom
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-show-sbom:0.1@sha256:8e0f8cad75e6f674d72a874385b69c4651afc0c9dcc59feffe0d85844687d852
      - name: kind
        value: task
      resolver: bundles

  params:
  - description: Source Repository URL
    name: git-url
    type: string
  - default: ""
    description: Revision of the Source Repository
    name: revision
    type: string
  - default: "0"
    description: Depth of the git clone in number of commits. Use "1" for shallow clone. Use "0" for deep clone, i.e. to fetch all commits.
    name: clone-depth
    type: string
  - default: "true"
    description: Fetch tags with git clone
    name: clone-fetch-tags
    type: string
  - description: Output Image Repository
    name: output-image-repo
    type: string
  - default: "-fast"
    description: Suffix that will be appended to the output image tag.
    name: output-tag-suffix
    type: string
  - default: .
    description: Path to the source code of an application's component from where
      to build image.
    name: path-context
    type: string
  - default: Dockerfile
    description: Path to the Dockerfile inside the context specified by parameter
      path-context
    name: dockerfile
    type: string
  - default: "false"
    description: Force rebuild image
    name: rebuild
    type: string
  - default: "false"
    description: Skip checks against built image
    name: skip-checks
    type: string
  - default: "false"
    description: Execute the build with network isolation
    name: hermetic
    type: string
  - default: ""
    description: Build dependencies to be prefetched by Cachi2
    name: prefetch-input
    type: string
  - default: "false"
    description: Java build
    name: java
    type: string
  - default: ""
    description: Image tag expiration time, time values could be something like
      1h, 2d, 3w for hours, days, and weeks, respectively.
    name: image-expires-after
    type: string
  - default: "true"
    description: Build a source image.
    name: build-source-image
    type: string
  - default: ""
    description: Build stage to target in container build
    name: build-target-stage
    type: string
  - default: [ ]
    description: List of scanner-data file names to fetch to include in the container build.
    name: blobs-to-fetch
    type: array
  - default: "1d"
    description: This sets the expiration time for intermediate OCI artifacts produced and used during builds after which they can be garbage collected.
    name: oci-artifact-expires-after
    type: string

  results:
  - description: ""
    name: IMAGE_URL
    value: $(tasks.build-image-manifest.results.IMAGE_URL)
  - description: ""
    name: IMAGE_DIGEST
    value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
  - description: ""
    name: CHAINS-GIT_URL
    value: $(tasks.clone-repository.results.url)
  - description: ""
    name: CHAINS-GIT_COMMIT
    value: $(tasks.clone-repository.results.commit)
  - description: ""
    name: JAVA_COMMUNITY_DEPENDENCIES
    value: $(tasks.build-container-amd64.results.JAVA_COMMUNITY_DEPENDENCIES)

  workspaces:
  - name: git-auth

  tasks:

  - name: init
    params:
    - name: image-url
      # We can't provide a StackRox-style tag because it is not known at this time (requires cloning source, etc.)
      # As a workaround, we still provide a unique tag that's based on a revision in order for this task to comply with
      # its expected input. We later actually add this tag on a built image with the build-image-manifest-konflux task.
      value: $(params.output-image-repo):konflux-$(params.revision)
    - name: rebuild
      value: $(params.rebuild)
    - name: skip-checks
      value: $(params.skip-checks)
    taskRef:
      params:
      - name: name
        value: init
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-init:0.2@sha256:596b7c11572bb94eb67d9ffb4375068426e2a8249ff2792ce04ad2a4bc593a63
      - name: kind
        value: task
      resolver: bundles

  - name: clone-repository
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
    - name: depth
      value: $(params.clone-depth)
    - name: fetchTags
      value: $(params.clone-fetch-tags)
    - name: ociStorage
      value: $(params.output-image-repo):konflux-$(params.revision).git
    - name: ociArtifactExpiresAfter
      value: $(params.oci-artifact-expires-after)
    taskRef:
      params:
      - name: name
        value: git-clone-oci-ta
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-git-clone-oci-ta:0.1@sha256:1178a65926b449c3603f7c0ecbb2d9311c0d7f1443c5164e952e7634a1d10142
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values: [ "true" ]
    workspaces:
    - name: basic-auth
      workspace: git-auth

  - name: determine-image-tag
    params:
    - name: TAG_SUFFIX
      value: $(params.output-tag-suffix)
    - name: SOURCE_ARTIFACT
      value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
    taskRef:
      name: determine-image-tag

  - name: fetch-scanner-data
    params:
    - name: blobs-to-fetch
      value: [ "$(params.blobs-to-fetch[*])" ]
    - name: SOURCE_ARTIFACT
      value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
    - name: ociStorage
      value: $(params.output-image-repo):konflux-$(params.revision).prefetch
    - name: ociArtifactExpiresAfter
      value: $(params.oci-artifact-expires-after)
    taskRef:
      name: fetch-scanner-data

  - name: prefetch-dependencies
    params:
    - name: input
      value: $(params.prefetch-input)
    - name: SOURCE_ARTIFACT
      value: $(tasks.fetch-scanner-data.results.SOURCE_ARTIFACT)
    - name: ociStorage
      value: $(params.output-image-repo):konflux-$(params.revision).prefetch
    - name: ociArtifactExpiresAfter
      value: $(params.oci-artifact-expires-after)
    taskRef:
      params:
      - name: name
        value: prefetch-dependencies-oci-ta
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-prefetch-dependencies-oci-ta:0.1@sha256:57979e1c289bfe09acb70401f35558a9032e749b398a43fea049c044f9d96afe
      - name: kind
        value: task
      resolver: bundles

  - name: build-container-amd64
    params:
    - name: IMAGE
      value: $(params.output-image-repo):$(tasks.determine-image-tag.results.IMAGE_TAG)-amd64
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: PREFETCH_INPUT
      value: $(params.prefetch-input)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    - name: TARGET_STAGE
      value: $(params.build-target-stage)
    - name: BUILD_ARGS
      value:
      - SCANNER_TAG=$(tasks.determine-image-tag.results.IMAGE_TAG)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    taskRef:
      params:
      - name: name
        value: buildah-oci-ta
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-buildah-oci-ta:0.2@sha256:7673118c1ee0e2616b12491b95deebc3d5733c670b3c2fee29e7ea7900c16fa5
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values: [ "true" ]

  - name: build-container-s390x
    params:
    - name: IMAGE
      value: $(params.output-image-repo):$(tasks.determine-image-tag.results.IMAGE_TAG)-s390x
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: PREFETCH_INPUT
      value: $(params.prefetch-input)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    - name: TARGET_STAGE
      value: $(params.build-target-stage)
    - name: BUILD_ARGS
      value:
      - SCANNER_TAG=$(tasks.determine-image-tag.results.IMAGE_TAG)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: PLATFORM
      value: linux/s390x
    taskRef:
      params:
      - name: name
        value: buildah-remote-oci-ta
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-buildah-remote-oci-ta:0.2@sha256:ab6bf7f81794957593f367542d0f8653452c037a55d9500ac21994250aadc0ce
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values: [ "true" ]

  - name: build-container-ppc64le
    params:
    - name: IMAGE
      value: $(params.output-image-repo):$(tasks.determine-image-tag.results.IMAGE_TAG)-ppc64le
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: PREFETCH_INPUT
      value: $(params.prefetch-input)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    - name: TARGET_STAGE
      value: $(params.build-target-stage)
    - name: BUILD_ARGS
      value:
      - SCANNER_TAG=$(tasks.determine-image-tag.results.IMAGE_TAG)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: PLATFORM
      value: linux/ppc64le
    taskRef:
      params:
      - name: name
        value: buildah-remote-oci-ta
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-buildah-remote-oci-ta:0.2@sha256:ab6bf7f81794957593f367542d0f8653452c037a55d9500ac21994250aadc0ce
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values: [ "true" ]

  - name: build-container-arm64
    params:
    - name: IMAGE
      value: $(params.output-image-repo):$(tasks.determine-image-tag.results.IMAGE_TAG)-arm64
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.path-context)
    - name: HERMETIC
      value: $(params.hermetic)
    - name: PREFETCH_INPUT
      value: $(params.prefetch-input)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    - name: TARGET_STAGE
      value: $(params.build-target-stage)
    - name: BUILD_ARGS
      value:
      - SCANNER_TAG=$(tasks.determine-image-tag.results.IMAGE_TAG)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    - name: PLATFORM
      value: linux/arm64
    taskRef:
      params:
      - name: name
        value: buildah-remote-oci-ta
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-buildah-remote-oci-ta:0.2@sha256:ab6bf7f81794957593f367542d0f8653452c037a55d9500ac21994250aadc0ce
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values: [ "true" ]

  - name: build-image-manifest
    params:
    - name: IMAGE
      value: $(params.output-image-repo):$(tasks.determine-image-tag.results.IMAGE_TAG)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    - name: IMAGES
      value:
      - $(tasks.build-container-amd64.results.IMAGE_REF)
      - $(tasks.build-container-s390x.results.IMAGE_REF)
      - $(tasks.build-container-ppc64le.results.IMAGE_REF)
      - $(tasks.build-container-arm64.results.IMAGE_REF)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    taskRef:
      params:
      - name: name
        value: build-image-manifest
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-build-image-manifest:0.1@sha256:09f84dc4c80fadd1ff06441137bd393f242a2db63a14ff76c4af6002bb882ab8
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values: [ "true" ]

  - name: build-image-manifest-konflux
    params:
    - name: IMAGE
      value: $(params.output-image-repo):konflux-$(params.revision)
    - name: COMMIT_SHA
      value: $(tasks.clone-repository.results.commit)
    - name: IMAGES
      value:
      - $(tasks.build-container-amd64.results.IMAGE_REF)
      - $(tasks.build-container-s390x.results.IMAGE_REF)
      - $(tasks.build-container-ppc64le.results.IMAGE_REF)
      - $(tasks.build-container-arm64.results.IMAGE_REF)
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.image-expires-after)
    taskRef:
      params:
      - name: name
        value: build-image-manifest
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-build-image-manifest:0.1@sha256:09f84dc4c80fadd1ff06441137bd393f242a2db63a14ff76c4af6002bb882ab8
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values: [ "true" ]

  - name: build-source-image
    params:
    - name: BINARY_IMAGE
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    - name: CACHI2_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
    taskRef:
      params:
      - name: name
        value: source-build-oci-ta
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-source-build-oci-ta:0.1@sha256:9ea6c027a7e025a9a18367b2608f69e824a388807ef8d9f33742a8f9ef387045
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(tasks.init.results.build)
      operator: in
      values: [ "true" ]
    - input: $(params.build-source-image)
      operator: in
      values: [ "true" ]

  - name: deprecated-base-image-check-amd64
    params:
    - name: IMAGE_URL
      value: $(tasks.build-container-amd64.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container-amd64.results.IMAGE_DIGEST)
    taskRef:
      params:
      - name: name
        value: deprecated-image-check
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-deprecated-image-check:0.4@sha256:6c389c2f670975cc0dfdd07dcb33142b1668bbfd46f6af520dd0ab736c56e7e9
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values: [ "false" ]

  - name: deprecated-base-image-check-s390x
    params:
    - name: IMAGE_URL
      value: $(tasks.build-container-s390x.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container-s390x.results.IMAGE_DIGEST)
    taskRef:
      params:
      - name: name
        value: deprecated-image-check
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-deprecated-image-check:0.4@sha256:6c389c2f670975cc0dfdd07dcb33142b1668bbfd46f6af520dd0ab736c56e7e9
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values: [ "false" ]

  - name: deprecated-base-image-check-ppc64le
    params:
    - name: IMAGE_URL
      value: $(tasks.build-container-ppc64le.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container-ppc64le.results.IMAGE_DIGEST)
    taskRef:
      params:
      - name: name
        value: deprecated-image-check
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-deprecated-image-check:0.4@sha256:6c389c2f670975cc0dfdd07dcb33142b1668bbfd46f6af520dd0ab736c56e7e9
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values: [ "false" ]

  - name: deprecated-base-image-check-arm64
    params:
    - name: IMAGE_URL
      value: $(tasks.build-container-arm64.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-container-arm64.results.IMAGE_DIGEST)
    taskRef:
      params:
      - name: name
        value: deprecated-image-check
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-deprecated-image-check:0.4@sha256:6c389c2f670975cc0dfdd07dcb33142b1668bbfd46f6af520dd0ab736c56e7e9
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values: [ "false" ]

  - name: clair-scan
    params:
    - name: image-digest
      value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-image-manifest.results.IMAGE_URL)
    taskRef:
      params:
      - name: name
        value: clair-scan
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-clair-scan:0.1@sha256:a1bbc7354d8dc8fef41caca236bde682fc6a9230065a5537f1dc1ca4f1e39e83
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values: [ "false" ]

  - name: sast-snyk-check
    params:
    - name: SOURCE_ARTIFACT
      value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
    taskRef:
      params:
      - name: name
        value: sast-snyk-check-oci-ta
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-sast-snyk-check-oci-ta:0.1@sha256:34cbe0117ca1d9fd5d2cb69690ae2eed4c7ad70c9d277a652e89db06a0357c9e
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values: [ "false" ]

  - name: clamav-scan
    params:
    - name: image-digest
      value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
    - name: image-url
      value: $(tasks.build-image-manifest.results.IMAGE_URL)
    taskRef:
      params:
      - name: name
        value: clamav-scan
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-clamav-scan:0.1@sha256:90c3e57d6062661698f187ec02ea2735cd7f54ebc9a2ca636ca9de38a2190a8f
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values: [ "false" ]

  - name: sbom-json-check
    params:
    - name: IMAGE_URL
      value: $(tasks.build-image-manifest.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
    taskRef:
      params:
      - name: name
        value: sbom-json-check
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/task-sbom-json-check:0.1@sha256:501181e78ec76a0a9083ffc275f5307ba5653a762259412bcffaeb314f13f8ec
      - name: kind
        value: task
      resolver: bundles
    when:
    - input: $(params.skip-checks)
      operator: in
      values: [ "false" ]
