apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/scanner?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "500"
    pipelinesascode.tekton.dev/on-cel-expression: (target_branch == "release-2.35" || target_branch.matches("^2\\.35\\..?")) && event in ["push", "pull_request"]
  labels:
    appstudio.openshift.io/application: acs-4-6
    appstudio.openshift.io/component: scanner-db-4-6
    pipelines.appstudio.openshift.io/type: build
  name: scanner-db-build
  namespace: rh-acs-tenant

spec:

  params:
  - name: dockerfile
    value: image/db/rhel/konflux.Dockerfile
  - name: git-url
    value: '{{source_url}}'
  - name: image-expires-after
    # TODO(ROX-24530): return expiration for non-released images to 13w
    value: '52w'
  - name: output-image-repo
    value: quay.io/rhacs-eng/scanner-db
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: rebuild
    value: 'true'
  # TODO(ROX-20234): Enable hermetic builds
  # - name: hermetic
  #   value: "true"
  # No language dependencies are required for scanner-db image.
  - name: prefetch-input
    value: ''
  - name: build-source-image
    value: 'true'
  - name: build-target-stage
    value: scanner-db
  - name: clone-depth
    value: '0'
  - name: clone-fetch-tags
    value: 'true'
  - name: blobs-to-fetch
    value: [ 'pg-definitions.sql.gz' ]

  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'

  timeouts:
    tasks: 1h
    finally: 10m
    pipeline: 1h10m


  pipelineRef:
    name: scanner-component-pipeline
