apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stackrox/scanner?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "500"
    pipelinesascode.tekton.dev/on-cel-expression: |
      (event == "pull_request" && body.action != "ready_for_review") ||
      (event == "push" && target_branch.matches("^(master|release-.*|refs/tags/.*)$"))
  labels:
    appstudio.openshift.io/application: acs
    appstudio.openshift.io/component: scanner-slim
    pipelines.appstudio.openshift.io/type: build
  name: scanner-slim-on-push
  namespace: rh-acs-tenant

spec:

  params:
  - name: dockerfile
    value: image/scanner/rhel/konflux.Dockerfile
  - name: git-url
    value: '{{source_url}}'
  - name: image-expires-after
    value: '13w'
  - name: output-image-repo
    value: quay.io/rhacs-eng/release-scanner-slim
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: rebuild
    value: 'true'
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: |
      [
        { "type": "gomod", "path": "." },
        { "type": "rpm", "path": "." }
      ]
  - name: build-source-image
    value: 'true'
  - name: build-target-stage
    value: scanner-slim
  - name: clone-depth
    value: '0'
  - name: clone-fetch-tags
    value: 'true'
  - name: blobs-to-fetch
    value: [ 'nvd-definitions.zip', 'k8s-definitions.zip', 'repo2cpe.zip', 'genesis_manifests.json' ]

  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'

  taskRunSpecs:
  - pipelineTaskName: build-container-amd64
    stepSpecs:
    # Provision more CPU to speed up build compared to the defaults.
    # https://github.com/redhat-appstudio/build-definitions/blob/main/task/buildah/0.1/buildah.yaml#L126
    #
    # This is not required for multi-arch builds, because they are performed off cluster
    - name: build
      computeResources:
        requests:
          cpu: 2

  taskRunTemplate:
    serviceAccountName: build-pipeline-scanner-slim

  # Multiarch builds sometimes make the pipeline timeout after 1h.
  timeouts:
    tasks: 1h30m
    finally: 10m
    pipeline: 1h40m

  pipelineRef:
    name: scanner-component-pipeline
