FROM alpine:3.10

SHELL ["/bin/sh", "-o", "pipefail", "-c"]

# Scanner requires the following binaries.
RUN apk update && \
    apk --no-cache add \
            ca-certificates \
            bzr \
            git \
            openssl \
            xz \
        && apk --repository "http://nl.alpinelinux.org/alpine/3.10/community" --no-cache add rpm \
        && apk --purge del apk-tools;


COPY ./bin/scanner /
COPY ./bin/clairify /

ENTRYPOINT ["/scanner"]
